# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38db29cbae1fae0e59142fc9d916215154e2b50bb7f0e1fb5a2ae38d8fb72105a851af47dde884f582dfa8c81f43700efa18f7ace612a9c69ed29c7ac4c945b6

test:
  secret_key_base: 5703bfcdbf4134d38dfcdf3e40fc7659936c720a0a82bb011f1a737cb0bc7b35bc98ea2962feee8a2eb9f7463dddb013408a618b582bb0f58e15f955a90d6683

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
